### ISSUE TITLE
Package installation issue from zip file

### ISSUE THREAD

**Issue by kmc8c3** [zrmacc/MCC#3]
There seems to be an issue when you try to install the package from the zip file available on the website. I downloaded the code from 2 locations and the installation doesn't work. Is it that the name of these zip files - MCC-master and MCC-0.7.0 instead of just MCC?

https://github.com/zrmacc/MCC?tab=readme-ov-file (MCC-master.zip)

https://github.com/zrmacc/MCC/releases/tag/v0.7.0 (MCC-0.7.0)

**Comment by zrmacc** [comment]
Hello, thanks for your interest in the package. The package passes `R CMD CHECK --as-cran` and `devtools::install_github(repo = "zrmacc/MCC")` is working as well, so I do not think there is an issue with the code. MCC requires compilation, if working on a Mac, please ensure the [necessary dependencies](https://cloud.r-project.org/bin/macosx/) have been installed.
